// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq6pvP0XzKmkCMAuJYl_AzPxY-MmQt-bs',
    appId: '1:993481657736:web:cdaa968414a726519d7e3d',
    messagingSenderId: '993481657736',
    projectId: 'skillmatch-b37cd',
    authDomain: 'skillmatch-b37cd.firebaseapp.com',
    storageBucket: 'skillmatch-b37cd.firebasestorage.app',
    measurementId: 'G-5P8QHERBQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5BbNP21xZe3xHRnLVu4H_q-IhAkaNGSU',
    appId: '1:993481657736:android:6f80a3aff54110619d7e3d',
    messagingSenderId: '993481657736',
    projectId: 'skillmatch-b37cd',
    storageBucket: 'skillmatch-b37cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM6ZY3j1de5lYhegYsZ704DkQlRYMqakA',
    appId: '1:993481657736:ios:2dcdde171190d7e89d7e3d',
    messagingSenderId: '993481657736',
    projectId: 'skillmatch-b37cd',
    storageBucket: 'skillmatch-b37cd.firebasestorage.app',
    iosBundleId: 'com.skillmatchteam.skillmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM6ZY3j1de5lYhegYsZ704DkQlRYMqakA',
    appId: '1:993481657736:ios:2a7c39fed11344aa9d7e3d',
    messagingSenderId: '993481657736',
    projectId: 'skillmatch-b37cd',
    storageBucket: 'skillmatch-b37cd.firebasestorage.app',
    iosBundleId: 'com.example.skillmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq6pvP0XzKmkCMAuJYl_AzPxY-MmQt-bs',
    appId: '1:993481657736:web:ff2f32e6dc32f7fe9d7e3d',
    messagingSenderId: '993481657736',
    projectId: 'skillmatch-b37cd',
    authDomain: 'skillmatch-b37cd.firebaseapp.com',
    storageBucket: 'skillmatch-b37cd.firebasestorage.app',
    measurementId: 'G-R237W8YERE',
  );
}
